/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserFollowingRouteImport } from './routes/user-following'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PostDraftsRouteImport } from './routes/post-drafts'
import { Route as PinsRouteImport } from './routes/pins'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotiRouteImport } from './routes/noti'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BrowseHistoryRouteImport } from './routes/browse-history'
import { Route as BlockedUserListRouteImport } from './routes/blocked-user-list'
import { Route as AddPostRouteImport } from './routes/add-post'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as AdminPanelDashboardRouteImport } from './routes/admin-panel/dashboard'
import { Route as AdminPanelAllPendingTagsRouteImport } from './routes/admin-panel/all-pending-tags'
import { Route as PublicProfileUserUserIdRouteImport } from './routes/public-profile/user/$userId'
import { Route as PostsTagTagNameRouteImport } from './routes/posts/tag/$tagName'

const UserFollowingRoute = UserFollowingRouteImport.update({
  id: '/user-following',
  path: '/user-following',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostDraftsRoute = PostDraftsRouteImport.update({
  id: '/post-drafts',
  path: '/post-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const PinsRoute = PinsRouteImport.update({
  id: '/pins',
  path: '/pins',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotiRoute = NotiRouteImport.update({
  id: '/noti',
  path: '/noti',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseHistoryRoute = BrowseHistoryRouteImport.update({
  id: '/browse-history',
  path: '/browse-history',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedUserListRoute = BlockedUserListRouteImport.update({
  id: '/blocked-user-list',
  path: '/blocked-user-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPostRoute = AddPostRouteImport.update({
  id: '/add-post',
  path: '/add-post',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelDashboardRoute = AdminPanelDashboardRouteImport.update({
  id: '/admin-panel/dashboard',
  path: '/admin-panel/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelAllPendingTagsRoute =
  AdminPanelAllPendingTagsRouteImport.update({
    id: '/admin-panel/all-pending-tags',
    path: '/admin-panel/all-pending-tags',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicProfileUserUserIdRoute = PublicProfileUserUserIdRouteImport.update({
  id: '/public-profile/user/$userId',
  path: '/public-profile/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsTagTagNameRoute = PostsTagTagNameRouteImport.update({
  id: '/posts/tag/$tagName',
  path: '/posts/tag/$tagName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-post': typeof AddPostRoute
  '/blocked-user-list': typeof BlockedUserListRoute
  '/browse-history': typeof BrowseHistoryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/noti': typeof NotiRoute
  '/notifications': typeof NotificationsRoute
  '/pins': typeof PinsRoute
  '/post-drafts': typeof PostDraftsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/setting': typeof SettingRoute
  '/terms': typeof TermsRoute
  '/user-following': typeof UserFollowingRoute
  '/admin-panel/all-pending-tags': typeof AdminPanelAllPendingTagsRoute
  '/admin-panel/dashboard': typeof AdminPanelDashboardRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/posts/tag/$tagName': typeof PostsTagTagNameRoute
  '/public-profile/user/$userId': typeof PublicProfileUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-post': typeof AddPostRoute
  '/blocked-user-list': typeof BlockedUserListRoute
  '/browse-history': typeof BrowseHistoryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/noti': typeof NotiRoute
  '/notifications': typeof NotificationsRoute
  '/pins': typeof PinsRoute
  '/post-drafts': typeof PostDraftsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/setting': typeof SettingRoute
  '/terms': typeof TermsRoute
  '/user-following': typeof UserFollowingRoute
  '/admin-panel/all-pending-tags': typeof AdminPanelAllPendingTagsRoute
  '/admin-panel/dashboard': typeof AdminPanelDashboardRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/posts/tag/$tagName': typeof PostsTagTagNameRoute
  '/public-profile/user/$userId': typeof PublicProfileUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-post': typeof AddPostRoute
  '/blocked-user-list': typeof BlockedUserListRoute
  '/browse-history': typeof BrowseHistoryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/noti': typeof NotiRoute
  '/notifications': typeof NotificationsRoute
  '/pins': typeof PinsRoute
  '/post-drafts': typeof PostDraftsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/setting': typeof SettingRoute
  '/terms': typeof TermsRoute
  '/user-following': typeof UserFollowingRoute
  '/admin-panel/all-pending-tags': typeof AdminPanelAllPendingTagsRoute
  '/admin-panel/dashboard': typeof AdminPanelDashboardRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/posts/tag/$tagName': typeof PostsTagTagNameRoute
  '/public-profile/user/$userId': typeof PublicProfileUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-post'
    | '/blocked-user-list'
    | '/browse-history'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/noti'
    | '/notifications'
    | '/pins'
    | '/post-drafts'
    | '/privacy-policy'
    | '/profile'
    | '/register'
    | '/setting'
    | '/terms'
    | '/user-following'
    | '/admin-panel/all-pending-tags'
    | '/admin-panel/dashboard'
    | '/posts/$postId'
    | '/settings/notifications'
    | '/posts/tag/$tagName'
    | '/public-profile/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-post'
    | '/blocked-user-list'
    | '/browse-history'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/noti'
    | '/notifications'
    | '/pins'
    | '/post-drafts'
    | '/privacy-policy'
    | '/profile'
    | '/register'
    | '/setting'
    | '/terms'
    | '/user-following'
    | '/admin-panel/all-pending-tags'
    | '/admin-panel/dashboard'
    | '/posts/$postId'
    | '/settings/notifications'
    | '/posts/tag/$tagName'
    | '/public-profile/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-post'
    | '/blocked-user-list'
    | '/browse-history'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/noti'
    | '/notifications'
    | '/pins'
    | '/post-drafts'
    | '/privacy-policy'
    | '/profile'
    | '/register'
    | '/setting'
    | '/terms'
    | '/user-following'
    | '/admin-panel/all-pending-tags'
    | '/admin-panel/dashboard'
    | '/posts/$postId'
    | '/settings/notifications'
    | '/posts/tag/$tagName'
    | '/public-profile/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddPostRoute: typeof AddPostRoute
  BlockedUserListRoute: typeof BlockedUserListRoute
  BrowseHistoryRoute: typeof BrowseHistoryRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotiRoute: typeof NotiRoute
  NotificationsRoute: typeof NotificationsRoute
  PinsRoute: typeof PinsRoute
  PostDraftsRoute: typeof PostDraftsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingRoute: typeof SettingRoute
  TermsRoute: typeof TermsRoute
  UserFollowingRoute: typeof UserFollowingRoute
  AdminPanelAllPendingTagsRoute: typeof AdminPanelAllPendingTagsRoute
  AdminPanelDashboardRoute: typeof AdminPanelDashboardRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  PostsTagTagNameRoute: typeof PostsTagTagNameRoute
  PublicProfileUserUserIdRoute: typeof PublicProfileUserUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-following': {
      id: '/user-following'
      path: '/user-following'
      fullPath: '/user-following'
      preLoaderRoute: typeof UserFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-drafts': {
      id: '/post-drafts'
      path: '/post-drafts'
      fullPath: '/post-drafts'
      preLoaderRoute: typeof PostDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pins': {
      id: '/pins'
      path: '/pins'
      fullPath: '/pins'
      preLoaderRoute: typeof PinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noti': {
      id: '/noti'
      path: '/noti'
      fullPath: '/noti'
      preLoaderRoute: typeof NotiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse-history': {
      id: '/browse-history'
      path: '/browse-history'
      fullPath: '/browse-history'
      preLoaderRoute: typeof BrowseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked-user-list': {
      id: '/blocked-user-list'
      path: '/blocked-user-list'
      fullPath: '/blocked-user-list'
      preLoaderRoute: typeof BlockedUserListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-post': {
      id: '/add-post'
      path: '/add-post'
      fullPath: '/add-post'
      preLoaderRoute: typeof AddPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel/dashboard': {
      id: '/admin-panel/dashboard'
      path: '/admin-panel/dashboard'
      fullPath: '/admin-panel/dashboard'
      preLoaderRoute: typeof AdminPanelDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-panel/all-pending-tags': {
      id: '/admin-panel/all-pending-tags'
      path: '/admin-panel/all-pending-tags'
      fullPath: '/admin-panel/all-pending-tags'
      preLoaderRoute: typeof AdminPanelAllPendingTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-profile/user/$userId': {
      id: '/public-profile/user/$userId'
      path: '/public-profile/user/$userId'
      fullPath: '/public-profile/user/$userId'
      preLoaderRoute: typeof PublicProfileUserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/tag/$tagName': {
      id: '/posts/tag/$tagName'
      path: '/posts/tag/$tagName'
      fullPath: '/posts/tag/$tagName'
      preLoaderRoute: typeof PostsTagTagNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddPostRoute: AddPostRoute,
  BlockedUserListRoute: BlockedUserListRoute,
  BrowseHistoryRoute: BrowseHistoryRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotiRoute: NotiRoute,
  NotificationsRoute: NotificationsRoute,
  PinsRoute: PinsRoute,
  PostDraftsRoute: PostDraftsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingRoute: SettingRoute,
  TermsRoute: TermsRoute,
  UserFollowingRoute: UserFollowingRoute,
  AdminPanelAllPendingTagsRoute: AdminPanelAllPendingTagsRoute,
  AdminPanelDashboardRoute: AdminPanelDashboardRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  PostsTagTagNameRoute: PostsTagTagNameRoute,
  PublicProfileUserUserIdRoute: PublicProfileUserUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
