/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserFollowingRouteImport } from './routes/user-following'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PublicProfileRouteImport } from './routes/public-profile'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PostDraftsRouteImport } from './routes/post-drafts'
import { Route as PinRouteImport } from './routes/pin'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotiRouteImport } from './routes/noti'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as BrowseHistoryRouteImport } from './routes/browseHistory'
import { Route as AddPostRouteImport } from './routes/add-post'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'

const UserFollowingRoute = UserFollowingRouteImport.update({
  id: '/user-following',
  path: '/user-following',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/public-profile',
  path: '/public-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostDraftsRoute = PostDraftsRouteImport.update({
  id: '/post-drafts',
  path: '/post-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const PinRoute = PinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotiRoute = NotiRouteImport.update({
  id: '/noti',
  path: '/noti',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseHistoryRoute = BrowseHistoryRouteImport.update({
  id: '/browseHistory',
  path: '/browseHistory',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPostRoute = AddPostRouteImport.update({
  id: '/add-post',
  path: '/add-post',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-post': typeof AddPostRoute
  '/browseHistory': typeof BrowseHistoryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/noti': typeof NotiRoute
  '/notifications': typeof NotificationsRoute
  '/pin': typeof PinRoute
  '/post-drafts': typeof PostDraftsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/public-profile': typeof PublicProfileRoute
  '/register': typeof RegisterRoute
  '/setting': typeof SettingRoute
  '/terms': typeof TermsRoute
  '/user-following': typeof UserFollowingRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-post': typeof AddPostRoute
  '/browseHistory': typeof BrowseHistoryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/noti': typeof NotiRoute
  '/notifications': typeof NotificationsRoute
  '/pin': typeof PinRoute
  '/post-drafts': typeof PostDraftsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/public-profile': typeof PublicProfileRoute
  '/register': typeof RegisterRoute
  '/setting': typeof SettingRoute
  '/terms': typeof TermsRoute
  '/user-following': typeof UserFollowingRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-post': typeof AddPostRoute
  '/browseHistory': typeof BrowseHistoryRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/noti': typeof NotiRoute
  '/notifications': typeof NotificationsRoute
  '/pin': typeof PinRoute
  '/post-drafts': typeof PostDraftsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/public-profile': typeof PublicProfileRoute
  '/register': typeof RegisterRoute
  '/setting': typeof SettingRoute
  '/terms': typeof TermsRoute
  '/user-following': typeof UserFollowingRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-post'
    | '/browseHistory'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/noti'
    | '/notifications'
    | '/pin'
    | '/post-drafts'
    | '/privacy-policy'
    | '/profile'
    | '/public-profile'
    | '/register'
    | '/setting'
    | '/terms'
    | '/user-following'
    | '/settings/notifications'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-post'
    | '/browseHistory'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/noti'
    | '/notifications'
    | '/pin'
    | '/post-drafts'
    | '/privacy-policy'
    | '/profile'
    | '/public-profile'
    | '/register'
    | '/setting'
    | '/terms'
    | '/user-following'
    | '/settings/notifications'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-post'
    | '/browseHistory'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/noti'
    | '/notifications'
    | '/pin'
    | '/post-drafts'
    | '/privacy-policy'
    | '/profile'
    | '/public-profile'
    | '/register'
    | '/setting'
    | '/terms'
    | '/user-following'
    | '/settings/notifications'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddPostRoute: typeof AddPostRoute
  BrowseHistoryRoute: typeof BrowseHistoryRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotiRoute: typeof NotiRoute
  NotificationsRoute: typeof NotificationsRoute
  PinRoute: typeof PinRoute
  PostDraftsRoute: typeof PostDraftsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  PublicProfileRoute: typeof PublicProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingRoute: typeof SettingRoute
  TermsRoute: typeof TermsRoute
  UserFollowingRoute: typeof UserFollowingRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-following': {
      id: '/user-following'
      path: '/user-following'
      fullPath: '/user-following'
      preLoaderRoute: typeof UserFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-profile': {
      id: '/public-profile'
      path: '/public-profile'
      fullPath: '/public-profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-drafts': {
      id: '/post-drafts'
      path: '/post-drafts'
      fullPath: '/post-drafts'
      preLoaderRoute: typeof PostDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pin': {
      id: '/pin'
      path: '/pin'
      fullPath: '/pin'
      preLoaderRoute: typeof PinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noti': {
      id: '/noti'
      path: '/noti'
      fullPath: '/noti'
      preLoaderRoute: typeof NotiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browseHistory': {
      id: '/browseHistory'
      path: '/browseHistory'
      fullPath: '/browseHistory'
      preLoaderRoute: typeof BrowseHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-post': {
      id: '/add-post'
      path: '/add-post'
      fullPath: '/add-post'
      preLoaderRoute: typeof AddPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddPostRoute: AddPostRoute,
  BrowseHistoryRoute: BrowseHistoryRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotiRoute: NotiRoute,
  NotificationsRoute: NotificationsRoute,
  PinRoute: PinRoute,
  PostDraftsRoute: PostDraftsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  PublicProfileRoute: PublicProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingRoute: SettingRoute,
  TermsRoute: TermsRoute,
  UserFollowingRoute: UserFollowingRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
